//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestClient.PhonebookService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/telBookService")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string submitterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first {
            get {
                return this.firstField;
            }
            set {
                if ((object.ReferenceEquals(this.firstField, value) != true)) {
                    this.firstField = value;
                    this.RaisePropertyChanged("first");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last {
            get {
                return this.lastField;
            }
            set {
                if ((object.ReferenceEquals(this.lastField, value) != true)) {
                    this.lastField = value;
                    this.RaisePropertyChanged("last");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string submitter {
            get {
                return this.submitterField;
            }
            set {
                if ((object.ReferenceEquals(this.submitterField, value) != true)) {
                    this.submitterField = value;
                    this.RaisePropertyChanged("submitter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel {
            get {
                return this.telField;
            }
            set {
                if ((object.ReferenceEquals(this.telField, value) != true)) {
                    this.telField = value;
                    this.RaisePropertyChanged("tel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PhonebookService.ItelBookService")]
    public interface ItelBookService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItelBookService/submitkontakt", ReplyAction="http://tempuri.org/ItelBookService/submitkontaktResponse")]
        void submitkontakt(WCFTestClient.PhonebookService.Contact kontakt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItelBookService/getContacts", ReplyAction="http://tempuri.org/ItelBookService/getContactsResponse")]
        WCFTestClient.PhonebookService.Contact[] getContacts();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItelBookServiceChannel : WCFTestClient.PhonebookService.ItelBookService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItelBookServiceClient : System.ServiceModel.ClientBase<WCFTestClient.PhonebookService.ItelBookService>, WCFTestClient.PhonebookService.ItelBookService {
        
        public ItelBookServiceClient() {
        }
        
        public ItelBookServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItelBookServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItelBookServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItelBookServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void submitkontakt(WCFTestClient.PhonebookService.Contact kontakt) {
            base.Channel.submitkontakt(kontakt);
        }
        
        public WCFTestClient.PhonebookService.Contact[] getContacts() {
            return base.Channel.getContacts();
        }
    }
}
